from classes.Jugador import Jugador
from classes.Partido import Partido
from classes.Equipo import Equipo
from classes.Torneo import Torneo
from datetime import date

j = Jugador()
j2 = Jugador()
j3 = Jugador()
j4 = Jugador()
e = Equipo()
e2 = Equipo()
e3 = Equipo()
e4 = Equipo()
p = Partido()
t = Torneo()

j.setNombre("Pepe")
j.setFechaNac(date(2000,3,13))
j.setNroCamiseta(32)
j2.setNombre("Juan")
j2.setFechaNac(date(2001,2,15))
j2.setNroCamiseta(31)
j.setNombre("Viti")
j.setFechaNac(date(2000,3,12))
j.setNroCamiseta(30)
j2.setNombre("Chu8amn")
j2.setFechaNac(date(2001,2,24))
j2.setNroCamiseta(29)
e.setNombre("Nose")
e.modifDisponibilidad(1,2,True)
e.agregarJugador(j)
e.setCapitan(j)
e2.setNombre("Nose2")
e2.modifDisponibilidad(1,2,True)
e2.agregarJugador(j2)
e2.setCapitan(j2)
e3.setNombre("Nose3")
e3.modifDisponibilidad(1,2,True)
e3.agregarJugador(j3)
e3.setCapitan(j3)
e4.setNombre("Nose4")
e4.modifDisponibilidad(1,2,True)
e4.agregarJugador(j4)
e4.setCapitan(j4)
print(e.listaJugadores[0].nroCamiseta)
